### ISSUE TITLE
Entscheide mit Indexzahl berechnen

### ISSUE THREAD

**Issue by schnellschnell** [mietrechtspraxis/mietrecht_ch#4]
Backend-Problem von https://github.com/mietrechtspraxis/mietrecht-ch-frontend/issues/23

https://github.com/mietrechtspraxis/mietrecht_ch/blob/develop/mietrecht_ch/mietrecht_ch/doctype/rent/api.py

**Comment by schnellschnell** [comment]
@sacovo
Beispiel für Eingabe: https://legacy.mietrecht.ch/db/mr_mietzins_frei.php?Miete%5BHaupt%5D=1175&Miete%5BNeben%5D=0&Hypo%5BZinsVon%5D=1.50&Hypo%5BZinsBis%5D=1.75&Teu%5BTeuVon%5D=106.3&Teu%5BTeuBis%5D=107.1&Kost%5BPSatz%5D=0.25&Kost%5BMonatVon%5D=8&Kost%5BJahrVon%5D=2023&Kost%5BMonatBis%5D=4&Kost%5BJahrBis%5D=2024&Sond%5BWertAbs%5D=0&Sond%5BWertPrz%5D=0&Sond%5BResAbs%5D=0&Sond%5BResPrz%5D=0

Bzw. 
```
curl 'https://mp.libracore.ch/api/method/mietrecht_ch.mietrecht_ch.doctype.rent.api.compute_rent' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: https://www.mietrecht.ch' \
  -H 'Referer: https://www.mietrecht.ch/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"canton":null,"rent":{"rent":1175,"extraRoom":null},"hypoReference":{"previous":{"day":null,"month":"1","year":"2024","rate":1.5},"next":{"day":null,"month":"4","year":"2024","rate":1.75},"inputType":"manual"},"inflation":{"basis":"2000-05-01","inputType":"manual","previous":{"month":"2","year":"2024","index":"106.3"},"next":{"month":"4","year":"2024","index":"107.1"}},"generalCostsIncrease":{"flatRate":0.25,"previous":{"month":"8","year":"2023"},"next":{"month":"4","year":"2024"}}}'
```

 Das Problem mit `BadRequestException(\\nmietrecht_ch.models.exceptions.mietrechtException.BadRequestException: No value provided for canton` kommt von __validation_data__(payload) bzw. def __canton_validation__(payload). Leider kann man es nicht einfach in compute_rent() auskommentieren. (Einen Kanton kann es hier nicht haben, da es genau die manuelle Eingabe ist.)

**Comment by sacovo** [comment]
Ich habe mal die Überprüfung geändert, funktioniert das so?

Und beim Testen ist mir noch ein Problem aufgefallen, wenn ein Betrag für den Nebenraum eingegeben wird, ich weiss nicht, ob die Korrektur so reicht.

Siehe PR: #5
